import { z } from 'zod';
const count = z.number().int().nonnegative();
export const sirosProgressSchema = z.discriminatedUnion('state', [z.object({state:z.literal('missing')}),z.object({state:z.literal('failed')}),z.object({state:z.literal('review'),sourceDate:z.iso.date(),researchedRows:count,directionKeys:count,futureMissing:count,existingProofCandidates:count,coreRows:count,plannedDirections:z.array(z.object({key:z.string().regex(/^[A-Z0-9]{2,3}:[A-Z]{3}-[A-Z]{3}$/),effectiveFrom:z.iso.date(),effectiveUntil:z.iso.date()})).optional(),newSelectable:z.literal(0),publicPackage:z.literal('notice-review')})]);
const sirosBrazilCarrierProgress=z.object({registeredDirections:count,eligibleRows:count,mappedAirportRows:count,periodRows:count,scheduledOnSnapshotDateRows:count,futureRows:count,publishedOverlapRows:count,nonPublishedOverlapRows:count,novelCurrentDirections:count,novelFutureDirections:count,designatorQuarantineRows:count}).strict();
export const sirosBrazilBulkProgressSchema=z.discriminatedUnion('state',[z.object({state:z.literal('failed')}).strict(),z.object({state:z.literal('stale'),reviewRuntimeSHA256:z.string().regex(/^[a-f0-9]{64}$/),currentRuntimeSHA256:z.string().regex(/^[a-f0-9]{64}$/)}).strict(),z.object({state:z.literal('reviewed'),sourceDate:z.iso.date(),sourceSHA256:z.string().regex(/^[a-f0-9]{64}$/),mappingVerifiedOn:z.iso.date(),runtimeSHA256:z.string().regex(/^[a-f0-9]{64}$/),eligibleRegularPassengerStatusDateRows:count,mappedAirportRows:count,heldEndpointRows:count,directions:count,distinctAirportPairs:count,novelDirections:count,novelPhysicalPairs:count,publishedPhysicalPairOverlapPairs:count,novelDirectionsWithExistingPhysicalPair:count,currentIntervalRows:count,scheduledOnSnapshotDateRows:count,futureStartRows:count,novelCurrentDirections:count,novelFutureOnlyDirections:count,publishedOverlapRows:count,nonPublishedOverlapRows:count,airportMappingGaps:count,designatorQuarantineRows:count,clockConflictPairs:count,acceptedCurrentRoutes:z.literal(0),readyImports:z.literal(0),qualifiedPackageImports:z.literal(0),publicDistribution:z.literal('notice-review'),licenseVersion:z.null(),byCarrier:z.object({JJ:sirosBrazilCarrierProgress,G3:sirosBrazilCarrierProgress,AD:sirosBrazilCarrierProgress}).strict(),examples:z.array(z.object({key:z.string().regex(/^[A-Z0-9]{2,3}:[A-Z]{3}-[A-Z]{3}$/),pair:z.string().regex(/^[A-Z]{3}-[A-Z]{3}$/),registrationRows:count,futureOnly:z.boolean(),physicalPairPublishedOverlap:z.boolean()})).max(5)}).strict()]);
export const palSummerInventoryProgressSchema=z.discriminatedUnion('state',[z.object({state:z.literal('failed')}).strict(),z.object({state:z.literal('reviewed'),sourceDate:z.iso.date(),serviceWindow:z.object({from:z.iso.date(),until:z.iso.date()}).strict(),factsSHA256:z.string().regex(/^[a-f0-9]{64}$/),sourceRows:count,normalizedDirections:count,distinctOrderedAirportDirections:count,uniqueAirports:count,bidirectionalPairs:count,marketingCarrier:z.literal('PR'),operatorIdentity:z.literal('unresolved-per-flight'),stopFieldsPresent:z.literal(false),exactRuntimeKeys:count,exactPublishedKeys:count,exactNonPublishedKeys:count,exactMissingKeys:count,publishedPhysicalDirectionCoverage:count,noPublishedPhysicalDirectionCoverage:count,heldNoTopologyProof:count,admittedRoutes:z.literal(0)}).strict()]);
export const skyteamSirosProgressSchema=z.discriminatedUnion('state',[z.object({state:z.literal('failed')}),z.object({state:z.literal('enriched'),sourceDate:z.iso.date(),sourceCapturedAt:z.iso.datetime(),sourceLastModified:z.string(),registrations:count,currentIntervalRegistrations:count,directions:z.array(z.object({key:z.string(),registrations:count})),future:z.array(z.object({key:z.string(),registrations:count,from:z.iso.date(),until:z.iso.date()})),heldRecords:count,newCurrentDirections:z.literal(0),newSelectable:z.literal(0),publicPackage:z.literal('notice-review')})]);
export const avinorSemanticProgressSchema=z.discriminatedUnion('state',[z.object({state:z.literal('failed')}),z.object({state:z.literal('reviewed'),sourceDate:z.iso.date(),sourceCapturedAt:z.iso.datetime(),sourceLastUpdate:z.iso.datetime(),sourceWindow:z.object({from:z.iso.datetime().nullable(),until:z.iso.datetime().nullable()}),documentation:z.object({url:z.url(),path:z.string(),sha256:z.string(),retrievedAt:z.string()}),rawRecords:count,acceptedReferences:count,semanticEnrichedReferences:count,documentedDefaultPassengerScope:z.literal(true),regularVsCharterPerRow:z.literal('unknown'),cargoPerRow:z.literal('not-independently-verified'),operatingCompany:z.literal('unknown'),viaCompleteness:z.literal('not-guaranteed'),nextStageEndpoint:z.literal('not-established'),clock:z.literal('UTC-scheduled-reference'),directions:z.array(z.object({key:z.string(),records:count,existingPublished:z.boolean(),fullMemberAtSourceDate:z.boolean(),rowIds:z.array(count)})),unmatchedDirections:count,unmatchedRecords:count,matchedDirections:count,matchedRecords:count,unmatchedMemberDirections:count,ambiguousEndpoints:z.array(z.object({id:z.string(),flightId:z.string(),peerAirport:z.string(),viaAirports:z.array(z.string()),qualification:z.enum(['multi-stop','circular','nonstop-unverified']),sourceListedPair:z.null(),firstStagePair:z.null()})),held:z.array(z.object({row:count,id:z.string(),reason:z.string()})),codeshareAliases:count,currentAdditions:z.literal(0),newSelectable:z.literal(0),sourceRequests:z.literal(0),minimumRefreshSeconds:z.number().int().min(180)})]);
export const airportMetadataReviewSchema=z.discriminatedUnion('state',[z.object({state:z.literal('failed')}).strict(),z.object({state:z.literal('reviewed'),sourceDate:z.iso.date(),sourceSHA256:z.string().regex(/^[a-f0-9]{64}$/),sourceCandidates:count,flaggedYesCandidates:count,appCatalogBefore:count,appCatalogAfter:count,flaggedYesMappedAfter:count,remainingFlaggedYesCandidates:count,admittedMetadataRows:count,heldFlaggedYesOutsideAirportTypeScope:count,heldSeaplaneBases:count,heldHeliports:count,runtimeSHA256:z.string().regex(/^[a-f0-9]{64}$/),runtimeRoutes:count,runtimePublishedRoutes:count,newRouteDirections:z.literal(0),currentServiceEstablished:z.literal(false)}).strict()]);
export const routeEvidenceStatusSchema=z.discriminatedUnion('state',[z.object({state:z.literal('failed')}).strict(),z.object({
 state:z.literal('verified'),asOf:z.iso.date(),validatedAtUTC:z.iso.datetime(),testFiles:count,testSuites:count,testsPassed:count,testsFailed:z.literal(0),airports:count,runtimeRoutes:count,runtimePublishedRoutes:count,runtimeSHA256:z.string().regex(/^[a-f0-9]{64}$/),
 brazil:z.object({previousBatchDirections:count,recentBatchDirections:count,internationalBatchDirections:count,genericCarrierBatchDirections:count,validatedDirections:count,boardRows:count,exactBoardRows:count,heldBoardRows:count,ambiguousBoardRows:count,unmatchedBoardRows:count,evidenceTier:z.literal('provider-listed-directed'),actualOperatingCarrierConfirmed:z.literal(false),flightNumbersAdded:z.literal(false),roundTheWorldEligibilityEstablished:z.literal(false)}).strict(),
 argentina:z.object({source:z.string(),state:z.literal('research-ready'),tier:z.literal('historical-aggregate'),latestDataMonth:z.string().regex(/^\d{4}-\d{2}$/),rows:count,rawCarrierPairs:count,icaoAirportPairs:count,localFixtureState:z.literal('access-needed'),runtimeImports:z.literal(0),currentServiceEstablished:z.literal(false)}).strict(),
 historicalReferencePilots:z.array(z.object({source:z.string(),tier:z.literal('historical-reference-pilot'),runtimeImports:z.literal(0)}).strict()),
 accessPending:z.array(z.object({source:z.string(),state:z.enum(['access-needed','pending-verification']),lastObservedHttpStatus:z.number().int().nullable()} ).strict()),
 nextSourceGap:z.object({priority:z.number().int().positive(),sourceFamily:z.string(),state:z.literal('carrier-mapping-needed'),nextStep:z.string(),networkSearchNeeded:z.literal(false)}).strict()
}).strict()]);
export const dataProgressSchema = z.object({
  version: z.literal(1), generatedAt: z.iso.datetime(), routeEvidenceStatus:routeEvidenceStatusSchema.optional(),
  state: z.enum(['verified', 'missing', 'failed']), reviews:z.object({airportMetadataCollection:airportMetadataReviewSchema.optional(),siros:sirosProgressSchema,sirosSkyteam:skyteamSirosProgressSchema.optional(),sirosBrazilBulk:sirosBrazilBulkProgressSchema.optional(),palSummerInventory:palSummerInventoryProgressSchema.optional(),avinorSemantics:avinorSemanticProgressSchema.optional()}).optional(),
  legacy: z.object({ total: count, published: count }).nullable(),
  qualified: z.object({ airports: count, routes: count, services: count, board: count, historical: count, endpoints: count, avinor: z.object({ references: count, rawFlights: count, held: count, capturedAt: z.iso.datetime(), from: z.iso.datetime(), until: z.iso.datetime(), confirmedNonstopDirections: z.literal(0) }).optional(), sourceDate: z.iso.date() }).nullable(),
}).strict().refine(value => (value.state === 'verified') === (value.qualified !== null), { message: 'Verified status requires qualified counts' });
export type DataProgress = z.infer<typeof dataProgressSchema>;
/** A rebuild is not a source refresh. Seven days is a display reminder only. */
export function progressIsStale(data: DataProgress, now: Date): boolean {
  const date = data.qualified?.sourceDate ?? data.generatedAt;
  return now.getTime() - Date.parse(date) > 7 * 86400000;
}

/** Source-window expiry is independent of the general seven-day reminder. */
export function avinorWindowExpired(data: DataProgress, now: Date): boolean {
  return data.qualified?.avinor !== undefined && now.getTime() > Date.parse(data.qualified.avinor.until);
}
