export interface SirosHistoricalDirectionTotals {readonly directions:number;readonly matched:number;readonly unmatched:number;readonly actualRows:number;}
export interface SirosResearchAliasDirection {readonly key:string;readonly registeredOperatorIATA:string;readonly rawOperatorICAO:string;readonly rawOriginICAO:string;readonly rawDestinationICAO:string;readonly originIATA:string;readonly destinationIATA:string;readonly actualRows:number;readonly firstDepartureLocalDate:string|null;readonly lastDepartureLocalDate:string|null;readonly queryDateEligible:boolean;readonly resolution:{readonly rule:'source-qualified-research-alias';readonly aliasICAO:'SBDO';readonly aliasIATA:'DOU';readonly validFrom:string;readonly sirosSourceDate:string;readonly vraDepartureMonth:string;readonly cachedAirportRowId:string;readonly cachedSourceSHA256:string;readonly coordinatesChanged:false};readonly passengerOrCargo:'unknown';readonly nonstop:'unknown';}
export interface SirosDouradosAliasQualification {readonly rule:string;readonly identity:{readonly rawICAO:'SBDO';readonly iata:'DOU';readonly airportName:string;readonly validFrom:string;readonly priorICAO:'SSDO';readonly priorValidThrough:string;readonly cachedSource:{readonly sourceId:string;readonly sha256:string;readonly bytes:number;readonly rowId:string;readonly rawIdentifier:string;readonly rawIata:string;readonly priorCoordinateIdentityUnchanged:true};readonly primaryEvidence:readonly {readonly authority:string;readonly document:string;readonly supports:string}[];readonly scope:string};readonly baseline:{readonly directionTotals:SirosHistoricalDirectionTotals;readonly queryDateDirectionTotals:SirosHistoricalDirectionTotals;readonly heldEndpointRows:number;readonly heldEndpointDirections:number;readonly otherEligibilityHeldRows:number};readonly researchOverlay:{readonly resolvedEndpointRows:number;readonly resolvedDirections:number;readonly queryDateResolvedDirections:number;readonly directions:readonly SirosResearchAliasDirection[];readonly postAliasDirectionTotals:SirosHistoricalDirectionTotals;readonly postAliasQueryDateDirectionTotals:SirosHistoricalDirectionTotals;readonly remainingHeldEndpointRows:0;readonly otherEligibilityHeldRowsPreserved:number;readonly importedCurrentRoutes:0;readonly importedQualifiedPackageRows:0;readonly coordinatesChanged:false;readonly rawSSDOHistoryPreserved:true};}
export interface SirosQueryPlan {
  readonly csvRow:number;readonly sourceSnapshotDate:string;readonly queryDate:string;readonly rawOperatorICAO:string;readonly registeredOperatorIATA:string;readonly registeredOperatorName:string;
  readonly key:string;readonly pair:readonly [string,string];readonly originICAO:string;readonly destinationICAO:string;
  readonly registrationId:string;readonly designatorRaw:string;readonly designatorTier:'usable-format'|'held-Z-prefixed'|'held-unrepresentable';
  readonly statusRaw:string;readonly effectiveFrom:string;readonly effectiveUntil:string;readonly weekdays:readonly number[];
  readonly scheduledOnSnapshotDate:boolean;readonly periodIncludesSnapshotDate:boolean;readonly periodTier:'active-interval-at-snapshot'|'future-start-at-snapshot'|'overlap-without-snapshot-weekday';
  readonly departureUTCRaw:string;readonly arrivalUTCRaw:string;readonly stageNumber:number;readonly codeshareRaw:string;
  readonly runtimeOverlap:'published'|'non-published'|'absent';readonly physicalDirectionPublished:boolean;readonly sourceSemantics:string;readonly overlappingClockConflict:boolean;
  readonly conflictOnQueryDate:boolean;readonly scheduleEvidenceKind:'registered-plan-only';readonly actualOperation:'unverified';readonly selectable:false;
}
export interface SirosQueryHeldEndpoint {
  readonly csvRow:number; readonly sourceSnapshotDate:string;readonly queryDate:string;readonly rawOperatorICAO:string; readonly registeredOperatorIATA:string;
  readonly registrationId:string; readonly originICAO:string; readonly destinationICAO:string;
  readonly effectiveFrom:string; readonly effectiveUntil:string; readonly weekdays:readonly number[];
  readonly designatorRaw:string; readonly designatorTier:'held-Z-prefixed'|'held-unrepresentable'|'usable-format';
  readonly departureUTCRaw:string; readonly arrivalUTCRaw:string; readonly stageNumberRaw:string;
  readonly codeshareRaw:string; readonly runtimeOverlap:'endpoint-unmapped';
  readonly selectable:false; readonly actualOperation:'unverified';
  readonly holdReason:string;
}
export interface SirosRegisteredQueryCatalog {
  readonly version:1; readonly sourceDate:string; readonly queryDate:string;
  readonly sourceSHA256:string; readonly sourceBytes:number; readonly mappingVerifiedOn:string;
  readonly queryWeekdayUTC:number; readonly eligibleMappedRows:number; readonly endpointHeldRows:number; readonly mappedRowsOutsideQueryDate:number; readonly heldEndpointRowsOutsideQueryDate:number;readonly otherEligibilityHeldRows:number;
  readonly operatorDirectionKeys:number; readonly airportDirections:number;
  readonly directionsAlreadyPresentAnyCarrier:number; readonly directionsAbsentAllCarriers:number;
  readonly conflictDirections:number;readonly historicalConflictDirections:number; readonly designatorQuarantineRows:number;
  readonly rows:readonly SirosQueryPlan[]; readonly held:readonly SirosQueryHeldEndpoint[];
  readonly historicalCorroboration?: {readonly source:{readonly sourceId:string;readonly sourceUrl:string;readonly sha256:string;readonly bytes:number;readonly departureMonth:string;readonly retrievedOn:string;readonly cacheOnly:true};readonly criteria:Record<string,unknown>;readonly eligibleActualRows:number;readonly targetCarrierEligibleActualRows:number;readonly otherCarrierEligibleActualRows:number;readonly targetCarrierRows:{readonly TAM:number;readonly GLO:number;readonly AZU:number};readonly excludedSourceRows:{readonly total:number;readonly cancelledOrOtherStatusRows:number;readonly missingOrInvalidActualTimestampRows:number;readonly realizedOutsideAugustRows:number};readonly plannedDirectionTotals:SirosHistoricalDirectionTotals;readonly byRegisteredOperator:Record<string,SirosHistoricalDirectionTotals>;readonly queryDateDirectionTotals:SirosHistoricalDirectionTotals;readonly directions:readonly {readonly key:string;readonly rawOperatorICAO:string;readonly originICAO:string;readonly destinationICAO:string;readonly actualRows:number;readonly firstDepartureLocalDate:string|null;readonly lastDepartureLocalDate:string|null;readonly firstArrivalLocalDate:string|null;readonly lastArrivalLocalDate:string|null;readonly passengerOrCargo:'unknown';readonly nonstop:'unknown'}[];readonly heldEndpointDirections:readonly {readonly rawOperatorICAO:string;readonly originICAO:string;readonly destinationICAO:string;readonly actualRows:number;readonly firstDepartureLocalDate:string|null;readonly lastDepartureLocalDate:string|null}[];readonly aliasQualification:SirosDouradosAliasQualification;readonly limits:readonly string[]};
  readonly boundaries:{readonly currentRouteAdmissions:0;readonly qualifiedPackageImports:0;readonly publicDistribution:'notice-review';readonly actualOperation:'unverified';readonly selectable:false};
}
